config/routes.rb
Rails.application.routes.draw do
  get 'sensei/index'
  post 'sensei/analyze'

  root 'sensei#index'
end

app/models/bsuir_finder.rb
require 'open-uri'

class BsuirFinder < ActiveRecord::Base
  GROUPS_URL = 'http://www.bsuir.by/schedule/rest/studentGroup'
  SCHEDULE_URL = 'http://www.bsuir.by/schedule/rest/schedule/'
  LECTORS_URL = 'http://bsuir-helper.ru/lectors'
  BSUIR_HELPER_URL = 'http://bsuir-helper.ru'

  def self.find_group_id(number)
    group_id = nil
    groups = Nokogiri::XML(open GROUPS_URL)
    group = groups.xpath('//studentGroup').find { |group| group.xpath('name').text == number }
    group.xpath('id').text if group
  end

  def self.parse_teacher(employee)
    { last_name: employee.xpath('lastName').text, first_name: employee.xpath('firstName').text,
        middle_name: employee.xpath('middleName').text, comments: [] }
  end

  def self.find_teachers(group_id)
    teachers = []
    schedule = Nokogiri::XML(open(SCHEDULE_URL + group_id.to_s))
    schedule.xpath('//employee').each do |employee|
      teacher = parse_teacher employee
      teachers << teacher
    end
    teachers.uniq!
  end

  def self.find_teachers_url(teacher)
    page = Nokogiri::HTML(open LECTORS_URL)
    references = page.xpath('//a')
    url = nil
    references.each do |reference|
      url = reference.values.first if reference.text.split.join(' ') == "#{teacher[:last_name]} #{teacher[:first_name]} #{teacher[:middle_name]}"
    end
    url
  end

  def self.find_comments(teacher)
    teacher_comments = []
    url = find_teachers_url teacher
    unless url.nil?
      page = Nokogiri::HTML(open(BSUIR_HELPER_URL + url))
      times = page.xpath("//div[@class='rounded-inside']/div/div[@class='submitted']/span[@class='comment-date']")
      comments = page.xpath("//div[@class='rounded-inside']/div/div[@class='content']/p")
      times.each_with_index do |time, index|
        teacher_comments << Opinion.new(teacher: "#{teacher[:last_name]} #{teacher[:first_name]} #{teacher[:middle_name]}",
          time: time.text, text: comments[index].text) #{ time: time.text, text: comments[index].text }
      end
    end
    teacher_comments
  end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
end

app/models/sentiment_analyzer.rb
require 'net/http'

class SentimentAnalyzer < ActiveRecord::Base
  SENTIMENT_ANALYZER_URL = 'https://russiansentimentanalyzer.p.mashape.com/rsa/sentiment/polarity/json/'
  ANALYZER_URI = URI(SENTIMENT_ANALYZER_URL)

  def self.analyze(text)
    request = Net::HTTP::Post.new(ANALYZER_URI)
    request['X-Mashape-Key'] = '43dvDjcWRWmsh6Zf8juVR6dmjZVwp1YuHfqjsn2prBDhAPMhqK'
    request['Content-Type'] = 'application.json'
    request['Accept'] = 'text/plain'
    request.body = { text: text, output_format: 'json' }.to_json
    
    http = Net::HTTP.new(ANALYZER_URI.hostname, ANALYZER_URI.port)
    http.use_ssl = true
    response = http.request(request)
    JSON.parse(response.body)['sentiment']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
end

app/controllers/sensei_controller.rb
class SenseiController < ApplicationController
  def index
  end

  def analyze
    group_id = BsuirFinder.find_group_id params[:group_number]
    flash[:alert] = 'Group not found' unless group_id

    if group_id
      teachers = BsuirFinder.find_teachers group_id
      @opinions = []
      teachers.each { |teacher| @opinions << BsuirFinder.find_comments(teacher) }
    end

    respond_to do |format|
      format.html { render @opinions.flatten }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/sensei_helper.rb
module SenseiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SenseiAnalyzer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='alert alert-warning'>
	<%= flash[:alert] %>
</div>
<%= yield %>

</body>
</html>

app/views/opinions/_opinion.html.erb
<div class='opinion'>	
	<p>Opinion about <b><i><%= opinion.teacher %></i></b> at <%= opinion.time %></p>
	<p><%= opinion.text %></p>
</div>

app/views/opinions/index.html.erb
<%= render @opinions %>

app/views/sensei/analyze.js.erb
$('div.alert-warning').text('<%= flash[:alert] %>');
var html = '<%= escape_javascript(render @opinions.flatten) %>';
$('div#opinions').html(html);

app/views/sensei/index.html.erb
<%= form_tag sensei_analyze_path, remote: true do %>
	<%= text_field_tag 'group_number', nil, maxlength: 6, placeholder: 'Group number', class: 'numeric' %>
	<%= submit_tag 'Get it!' %>
<% end %>
<div id='opinions'></div>